ingressClass:
  enabled: yes
  isDefaultClass: yes

service:
  spec:
    externalTrafficPolicy: Local

resources:
  requests: {}
  limits: {}

ports:
  traefik:
    port: 9000
    expose: no
    exposedPort: 9000
    protocol: TCP
  http:
    port: 8080
    expose: yes
    exposedPort: 80
    protocol: TCP
    redirectTo: https
  https:
    port: 8443
    expose: yes
    exposedPort: 443
    protocol: TCP
  mqtts:
    port: 8883
    expose: yes
    exposedPort: 8883
    protocol: TCP
