site_name: Mykilio
site_dir: public
site_url: https://mykil.io
repo_url: https://github.com/nicklasfrahm/mykilio
repo_name: nicklasfrahm/mykilio
edit_uri: edit/main/docs/
strict: yes
use_directory_urls: no
nav:
  - Home: index.md
  - Mykilio:
      - Overview: mykilio-overview.md
      - Architecture: mykilio-architecture.md
      - Resource properties: mykilio-resource-properties.md
      - Core API: mykilio-core-api.md
      - Baremetal API: mykilio-baremetal-api.md
      - Miscellaneous: mykilio-miscellaneous.md
  - Cremini:
      - Overview: cremini-overview.md
      - Management bus interface: cremini-management-bus-interface.md
      - Blade (ATmega328P): cremini-blade-atmega328p.md
  - Primo:
      - Overview: primo-overview.md
theme:
  name: material
  custom_dir: web/template
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
  palette:
    primary: teal
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - mdx_truly_sane_lists
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: yes
extra_css:
  - assets/css/home.css
