site_name: Mycelium
site_dir: public
site_url: https://mycelium.optrin.io
repo_url: https://github.com/nicklasfrahm/mycelium
repo_name: nicklasfrahm/mycelium
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Mycelium:
      - Overview: mycelium-overview.md
      - Properties: mycelium-properties.md
      - Miscellaneous: mycelium-miscellaneous.md
  - Mushroom:
      - Overview: mushroom-overview.md
      - Management bus interface: mushroom-management-bus-interface.md
      - Blade (ATmega328P): mushroom-blade-atmega328p.md
theme:
  name: material
  custom_dir: web/template
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
  palette:
    primary: teal
markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - mdx_truly_sane_lists
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.snippets
extra_css:
  - assets/css/home.css
