{{/* vim: set filetype=mustache: */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.controller.apiGroup | quote }}
    app.kubernetes.io/instance: {{ printf "%s-%s" .Values.controller.name .Release.Namespace | quote }}
    app.kubernetes.io/component: {{ .Chart.Name | quote }}
    app.kubernetes.io/part-of: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    helm.sh/chart: {{ .Chart.Name | quote }}
spec:
  replicas: {{ .Release.Replicas | quote }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  minReadySeconds: 15
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.controller.apiGroup | quote }}
      app.kubernetes.io/instance: {{ printf "%s-%s" .Values.controller.name .Release.Namespace | quote }}
      app.kubernetes.io/component: {{ .Chart.Name | quote }}
      app.kubernetes.io/part-of: {{ .Release.Namespace | quote }}
      app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
      helm.sh/chart: {{ .Chart.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.controller.apiGroup | quote }}
        app.kubernetes.io/instance: {{ printf "%s-%s" .Values.controller.name .Release.Namespace | quote }}
        app.kubernetes.io/component: {{ .Chart.Name | quote }}
        app.kubernetes.io/part-of: {{ .Release.Namespace | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        helm.sh/chart: {{ .Chart.Name | quote }}
    spec:
      initContainers:
        - name: permissions
          image: busybox
          command: [ "/bin/sh", "-c" ]
          args: [ "chown -vR 65532:65532 /certs" ]
          volumeMounts:
            - name: certs
              mountPath: "/certs"
          securityContext:
            runAsUser: 0
      containers:
        - name: {{ .Chart.Name | quote }}
          image: {{ printf "%s/%s:%s" .Values.container.registry .Values.container.repository .Values.container.tag | quote }}
          ports:
            - containerPort: {{ .Values.container.port }}
              name: http
          env:
            - name: PORT
              value: {{ .Values.container.port | quote }}
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-database" .Release.Name | quote }}
                  key: DATABASE_URI
            - name: BROKER_URI
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-broker" .Release.Name | quote }}
                  key: BROKER_URI
          volumeMounts:
            - name: certs
              mountPath: "/certs"
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 1
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 12
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      volumes:
        - name: certs
          secret:
            secretName: {{ printf "%s-certs" .Release.Name | quote }}
            defaultMode: 0600
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
