{{/* vim: set filetype=mustache: */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.controller.apiGroup }}
    app.kubernetes.io/instance: {{ printf "%s-%s" .Values.controller.name .Release.Namespace  }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: {{ .Release.Namespace }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.controller.apiGroup }}
    app.kubernetes.io/instance: {{ printf "%s-%s" .Values.controller.name .Release.Namespace  }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: {{ .Release.Namespace }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
