{{/* vim: set filetype=mustache: */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.controller.apiGroup | quote}}
    app.kubernetes.io/instance: {{ printf "%s-%s" .Values.controller.name .Release.Namespace | quote }}
    app.kubernetes.io/component: {{ .Chart.Name | quote }}
    app.kubernetes.io/part-of: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    helm.sh/chart: {{ .Chart.Name | quote }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.controller.apiGroup | quote}}
    app.kubernetes.io/instance: {{ printf "%s-%s" .Values.controller.name .Release.Namespace | quote }}
    app.kubernetes.io/component: {{ .Chart.Name | quote }}
    app.kubernetes.io/part-of: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    helm.sh/chart: {{ .Chart.Name | quote }}
  ports:
    - protocol: TCP
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
