ingressClass:
  enabled: yes
  isDefaultClass: yes

service:
  enabled: yes
  type: LoadBalancer

resources:
  requests: {}
  limits: {}

ports:
  traefik:
    port: 9000
    expose: no
    exposedPort: 9000
    protocol: TCP
  web:
    port: 8080
    expose: yes
    exposedPort: 80
    protocol: TCP
    ### This is temporarily disabled as hairpin NAT is not available in the current network.
    # redirectTo: websecure
  websecure:
    port: 8443
    expose: yes
    exposedPort: 443
    protocol: TCP
  mqtt:
    port: 1883
    expose: yes
    exposedPort: 1883
    protocol: TCP
  mqttsecure:
    port: 8883
    expose: yes
    exposedPort: 8883
    protocol: TCP
