replicaCount: 1
emqxConfig:
  EMQX_ALLOW_ANONYMOUS: "false"
  EMQX_LOADED_PLUGINS: emqx_management,emqx_recon,emqx_retainer,emqx_dashboard,emqx_auth_http
  EMQX_AUTH__HTTP__AUTH_REQ: https://$DOMAIN/apis/hooks.mykil.io/v1alpha1/authn
  EMQX_AUTH__HTTP__AUTH_REQ__METHOD: post
  EMQX_AUTH__HTTP__AUTH_REQ__HEADERS_CONTENTTYPE: application/json
  EMQX_AUTH__HTTP__AUTH_REQ__PARAMS: clientId=%c,username=%u,password=%P
