replicaCount: 1
recreatePods: true

emqxConfig:
  EMQX_ALLOW_ANONYMOUS: "false"
  EMQX_AUTH__HTTP__AUTH_REQ__URL: https://$DOMAIN/apis/core.mykil.io/v1alpha1/authn
  EMQX_AUTH__HTTP__AUTH_REQ__METHOD: post
  EMQX_AUTH__HTTP__AUTH_REQ__HEADERS__CONTENT_TYPE: application/json
  EMQX_AUTH__HTTP__AUTH_REQ__PARAMS: clientID=%c,username=%u,password=%P
  EMQX_AUTH__HTTP__SUPER_REQ__URL: ""
  EMQX_AUTH__HTTP__ACL_REQ__URL: ""

emqxLoadedPlugins: >
  {emqx_management, true}.
  {emqx_recon, true}.
  {emqx_retainer, true}.
  {emqx_dashboard, true}.
  {emqx_telemetry, true}.
  {emqx_rule_engine, true}.
  {emqx_auth_http, true}.
