name: alpha

on:
  push:
    branches:
      - main
    paths:
      - deployments/alpha/**
      - .github/workflows/alpha.yml
    tags:
      - v*
  pull_request:
    branches:
      - main
    paths:
      - deployments/alpha/**
      - .github/workflows/alpha.yml
  schedule:
    - cron: "0 0 * * *"
  workflow_run:
    workflows:
      - controllers
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

jobs:
  tls:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.event.workflow_run.conclusion != 'failure'
    runs-on: ubuntu-latest
    environment:
      name: alpha
    env:
      NAMESPACE: ${{ secrets.NAMESPACE }}
      DOMAIN: ${{ secrets.DOMAIN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Set up kubeconfig
        run: |
          mkdir -m 700 -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Provision namespace and TLS certificate
        run: |
          kubectl create ns $NAMESPACE || true
          cat deployments/alpha/tls-manifests.yml | envsubst | kubectl apply -f -

  emqx:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.event.workflow_run.conclusion != 'failure'
    runs-on: ubuntu-latest
    needs:
      - tls
    environment:
      name: alpha
    env:
      NAMESPACE: ${{ secrets.NAMESPACE }}
      DOMAIN: ${{ secrets.DOMAIN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Install helm
        uses: azure/setup-helm@v1

      - name: Set up kubeconfig
        run: |
          mkdir -m 700 -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Install emqx
        run: |
          kubectl create namespace $NAMESPACE || true
          helm repo add emqx https://repos.emqx.io/charts
          helm repo update
          cat deployments/alpha/emqx-values.yml | envsubst | helm upgrade \
            --install \
            --atomic \
            --namespace $NAMESPACE \
            --values - \
            emqx emqx/emqx
          cat deployments/alpha/emqx-manifests.yml | envsubst | kubectl apply -f -

  postgresql:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.event.workflow_run.conclusion != 'failure'
    runs-on: ubuntu-latest
    needs:
      - tls
    environment:
      name: alpha
    env:
      NAMESPACE: ${{ secrets.NAMESPACE }}
      POSTGRESQL_ADMIN_PASSWORD: ${{ secrets.POSTGRESQL_ADMIN_PASSWORD }}
      POSTGRESQL_REPLICATION_PASSWORD: ${{ secrets.POSTGRESQL_REPLICATION_PASSWORD }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Install helm
        uses: azure/setup-helm@v1

      - name: Set up kubeconfig
        run: |
          mkdir -m 700 -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Install postgresql
        run: |
          cat deployments/alpha/postgresql-manifests.yml | envsubst | kubectl apply -f -
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm upgrade \
            --install \
            --atomic \
            --namespace $NAMESPACE \
            --values deployments/alpha/postgresql-values.yml \
            postgresql bitnami/postgresql

  # The main point of this job is to synchronize the state
  # of the deployment in GitHub. In the future we could
  # set up some actual tests to evaluate the cluster health.
  test:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.event.workflow_run.conclusion != 'failure'
    runs-on: ubuntu-latest
    needs:
      - emqx
      - postgresql
    environment:
      name: alpha
    env:
      NAMESPACE: ${{ secrets.NAMESPACE }}
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Set up kubeconfig
        run: |
          mkdir -m 700 -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Display workloads and load
        run: |
          kubectl -n ${{ env.NAMESPACE }} get cert,ing,deploy,statefulset,pod
          kubectl -n ${{ env.NAMESPACE }} top pod
