name: alpha

on:
  push:
    branches:
      - main
    paths:
      - deployments/alpha/**
      - .github/workflows/alpha.yml
    tags:
      - v*
  pull_request:
    branches:
      - main
    paths:
      - deployments/alpha/**
      - .github/workflows/alpha.yml
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  emqx:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: alpha
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Check for envsubst
        run: which envsubst
