name: alpha

on:
  push:
    branches:
      - main
    paths:
      - deployments/alpha/**
      - .github/workflows/alpha.yml
    tags:
      - v*
  pull_request:
    branches:
      - main
    paths:
      - deployments/alpha/**
      - .github/workflows/alpha.yml
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  tls:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: alpha
    env:
      NAMESPACE: ${{ secrets.NAMESPACE }}
      DOMAIN: ${{ secrets.DOMAIN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Set up kubeconfig
        run: |
          mkdir -m 700 -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Provision namespace and TLS certificate
        run: |
          kubectl create ns $NAMESPACE || true
          cat deployments/alpha/certificate-manifests.yml | envsubst | kubectl apply -f -

  emqx:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs:
      - tls
    environment:
      name: alpha
    env:
      NAMESPACE: ${{ secrets.NAMESPACE }}
      DOMAIN: ${{ secrets.DOMAIN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Install helm
        uses: azure/setup-helm@v1

      - name: Set up kubeconfig
        run: |
          mkdir -m 700 -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Install emqx
        run: |
          kubectl create namespace $NAMESPACE || true
          helm repo add emqx https://repos.emqx.io/charts
          helm repo update
          cat deployments/alpha/emqx-values.yml | envsubst | helm upgrade \
            --install \
            --atomic \
            --namespace $NAMESPACE \
            --values - \
            emqx emqx/emqx
          cat deployments/alpha/emqx-manifests.yml | envsubst | kubectl apply -f -
