name: alpha

on:
  push:
    branches:
      - main
    paths:
      - deployments/alpha/**
      - .github/workflows/alpha.yml
    tags:
      - v*
  pull_request:
    branches:
      - main
    paths:
      - deployments/alpha/**
      - .github/workflows/alpha.yml
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  tls:
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: alpha
    env:
      NAMESPACE: ${{ secrets.NAMESPACE }}
      DOMAIN: ${{ secrets.DOMAIN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Set up kubeconfig
        run: |
          mkdir -m 700 -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Provision TLS certificate
        run: |
          cat deployments/alpha/certificate-manifests.yml | envsubst | kubectl apply -f -
