name: controllers

on:
  push:
    branches:
      - main
    paths:
      - go.mod
      - go.sum
      - Makefile
      - deployments/docker/**
      - .github/workflows/controllers.yml
      - "**/**.go"
    tags:
      - v*
  pull_request:
    branches:
      - main
    paths:
      - go.mod
      - go.sum
      - Makefile
      - deployments/docker/**
      - .github/workflows/controllers.yml
      - "**/**.go"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY: ghcr.io/${{ github.repository }}
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  controller:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        controller:
          - hooks
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Generate container metadata
        id: meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.REPOSITORY }}-${{ matrix.controller }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          file: deployments/container/Dockerfile
          cache-from: type=registry,ref=${{ env.REPOSITORY }}-${{ matrix.controller }}:main
          cache-to: type=inline
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ github.sha }}
            CONTROLLER=${{ matrix.controller }}
