name: infrastructure

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/infrastructure.yml
    tags:
      - v*
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/infrastructure.yml
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: infrastructure
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Check SSH connection
        uses: appleboy/ssh-action@master
        with:
          script_stop: true
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_TARGET_HOST }}
          fingerprint: ${{ secrets.SSH_TARGET_FINGERPRINT }}
          proxy_username: ${{ secrets.SSH_USER }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ secrets.SSH_PROXY_HOST }}
          proxy_fingerprint: ${{ secrets.SSH_PROXY_FINGERPRINT }}
          script: |
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--advertise-address $(host -t a edgerouterx-0.optrin.net) --tls-san edgerouterx-0.optrin.net" sudo sh -s -
